esphome:
  name: smo40-gw
  friendly_name: SMO40-GW

esp32:
  # Board schematic https://kmpelectronics.eu/wp-content/uploads/2019/12/ProDINoESP32-ETHv02-Schematic.pdf
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: WARN

# Enable Home Assistant API
api:
  encryption:
    key: "YOUR ENCRYPTION KEY"

ota:
  - platform: esphome
    password: "YOUR OTA KEY"

ethernet:
  type: W5500
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19
  cs_pin: GPIO33
  reset_pin: GPIO12

# Load nibe component
external_components:
  - source: 
      type: git
      url: https://github.com/elupus/esphome-nibe.git
    components: [ nibegw ]

uart:
  rx_pin: GPIO4
  tx_pin: GPIO16
  baud_rate: 9600

# Configure NibeGW
nibegw:
  dir_pin:
    number: GPIO2
    inverted: false

  udp:
    # The target address(s) to send data to. May be a multicast address.
    target:
      - ip: 192.168.X.Y # This is YOUR Home Assistant IP
        port: 9999 # The Nibe Home Assistant integration listens to 9999 by default 

    # List of source address to accept data from, may be empty for no filter
    source:
      - 192.168.X.Y # This is YOUR Home Assistant IP

  acknowledge:
    - MODBUS40

  # Constant replies to certain requests cabe made
  constants:
    - address: MODBUS40
      token: ACCESSORY
      data: [
            0x0A, # MODBUS version low
            0x00, # MODBUS version high
            0x01, # MODBUS address?
      ]

# Some helper functions to restart ESPHome from HA
button:
- platform: restart
  name: Nibegw Restart
- platform: safe_mode
  name: Nibegw Safe Mode Boot